site_name: 'py-app'
site_description: 'Main documentation for py-app'
repo_url: https://github.com/aumthakkar/2py-app
edit_uri: edit/main/docs

plugins:
  - techdocs-core
  
# For sidebar navigation on https://backstage.io/, see `microsite/sidebars.js`
nav:
  - Overview:
      - Getting started : 'docs/index.md'